packages:
  - "client"
  - "backend"

minimumReleaseAge: 10080
trustPolicy: no-downgrade
allowBuilds:
  "@firebase/util": true
  "@google/genai": true
  core-js: true
  esbuild: true
  protobufjs: true
