import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import "./LandingPage.css";
import "../base/colors.css";
/**
 * Se renderiza FUERA de <RouterProvider> (ver App.tsx) — vive en la raíz
 * real del dominio, antes de que el router (con basename "/app") tome el
 * control. Por eso los links de acá son <a href> normales, no <Link>/
 * useNavigate: cruzar a /app siempre implica una carga de página nueva,
 * no una transición de cliente.
 */
export default function LandingPage() {
    return (_jsxs("div", { className: "landing", children: [_jsxs("header", { className: "landing__header", children: [_jsx("span", { className: "landing__wordmark", children: "TheTavlo" }), _jsx("a", { className: "landing__navLink", href: "/app/login", children: "Iniciar sesi\u00F3n" })] }), _jsxs("main", { children: [_jsxs("section", { className: "landing__hero", children: [_jsxs("div", { className: "landing__heroText", children: [_jsx("h1", { children: "Tu semestre, en un solo panel." }), _jsx("p", { children: "Tareas, horario, notas y ex\u00E1menes en un mismo lugar \u2014 y lo compart\u00EDs con quien estudi\u00E1s, si quer\u00E9s." }), _jsxs("div", { className: "landing__ctaRow", children: [_jsx("a", { className: "landing__button landing__button--primary", href: "/app/login?onBoarding", children: "Crear cuenta gratis" }), _jsx("a", { className: "landing__button landing__button--ghost", href: "/app/login", children: "Iniciar sesi\u00F3n" })] })] }), _jsx("div", { className: "landing__mock", "aria-hidden": "true", children: _jsx(PanelMock, {}) })] }), _jsxs("section", { className: "landing__features", children: [_jsx(FeatureRow, { title: "Organiz\u00E1 todo por panel", description: "Cada materia, proyecto o grupo de estudio tiene su propio espacio \u2014 con tareas, notas y calendario adentro, no repartidos en cinco apps distintas.", align: "left" }), _jsx(FeatureRow, { title: "Tu horario, con asistencia", description: "Carg\u00E1s tus clases una vez. Si cambia el aula o el horario a mitad de cuatrimestre, TheTavlo guarda el historial en vez de pisar los datos viejos \u2014 y te deja anotar las faltas.", align: "right" }), _jsx(FeatureRow, { title: "Compartilo con tu grupo", description: "Invit\u00E1s por correo o mand\u00E1s un enlace. Vos decid\u00EDs si la otra persona puede editar el panel o solo mirarlo.", align: "left" }), _jsx(FeatureRow, { title: "Widgets, no una lista m\u00E1s", description: "Arm\u00E1s el panel con lo que de verdad quer\u00E9s ver: pr\u00F3ximos ex\u00E1menes, tareas pendientes, la semana que viene.", align: "right" })] }), _jsxs("section", { className: "landing__closing", children: [_jsx("h2", { children: "Empez\u00E1 gratis, no hace falta tarjeta." }), _jsx("a", { className: "landing__button landing__button--primary", href: "/app/login?onBoarding", children: "Crear cuenta gratis" })] })] }), _jsxs("footer", { className: "landing__footer", children: [_jsxs("span", { children: ["\u00A9 ", new Date().getFullYear(), " TheTavlo"] }), _jsx("a", { href: "/app/login", children: "Iniciar sesi\u00F3n" })] })] }));
}
/** Vista previa estática de un panel real — el "elemento con firma" de la página: mostrar el producto en vez de una ilustración genérica. */
function PanelMock() {
    return (_jsxs("div", { className: "panelMock", children: [_jsxs("div", { className: "panelMock__header", children: [_jsx("span", { className: "panelMock__dot" }), _jsx("span", { children: "C\u00E1lculo II" })] }), _jsxs("div", { className: "panelMock__row panelMock__row--done", children: [_jsx("span", { className: "panelMock__check" }), "Gu\u00EDa de l\u00EDmites"] }), _jsxs("div", { className: "panelMock__row", children: [_jsx("span", { className: "panelMock__check panelMock__check--empty" }), "Repasar derivadas"] }), _jsx("div", { className: "panelMock__divider" }), _jsx("div", { className: "panelMock__chip", children: "Lun 10:00 \u00B7 F\u00EDsica" }), _jsx("div", { className: "panelMock__chip panelMock__chip--accent", children: "Examen parcial \u00B7 14 oct" })] }));
}
function FeatureRow({ title, description, align, }) {
    return (_jsxs("div", { className: `featureRow featureRow--${align}`, children: [_jsx("h3", { children: title }), _jsx("p", { children: description })] }));
}
