import type { FirestoreDataConverter } from "firebase/firestore";
import type { Schedule } from "../domain/schedule.entity";
import type { Subject } from "../domain/subject.entity";
import type { ClassSlot } from "../domain/classSlot.entity";
import type { OccurrenceException } from "../domain/occurrenceException.entity";
import type { AttendanceRecord } from "../domain/attendanceRecord.entity";
export declare const scheduleConverter: FirestoreDataConverter<Schedule>;
export declare const subjectConverter: FirestoreDataConverter<Subject>;
export declare const classSlotConverter: FirestoreDataConverter<ClassSlot>;
export declare const occurrenceExceptionConverter: FirestoreDataConverter<OccurrenceException>;
export declare const attendanceRecordConverter: FirestoreDataConverter<AttendanceRecord>;
