import { type Mapper } from "#core/appCore/domain/AppCore.mapper";
import type { CreateScheduleDTO, Schedule } from "./schedule.entity";
import type { CreateSubjectDTO, Subject } from "./subject.entity";
import type { ClassSlot, CreateClassSlotDTO } from "./classSlot.entity";
import type { CreateOccurrenceExceptionDTO, OccurrenceException } from "./occurrenceException.entity";
import type { AttendanceRecord, UpsertAttendanceDTO } from "./attendanceRecord.entity";
export declare const ScheduleMapper: Mapper<Schedule, CreateScheduleDTO>;
export declare const SubjectMapper: Mapper<Subject, CreateSubjectDTO>;
export declare const ClassSlotMapper: Mapper<ClassSlot, CreateClassSlotDTO>;
export declare const OccurrenceExceptionMapper: Mapper<OccurrenceException, CreateOccurrenceExceptionDTO>;
export declare const AttendanceMapper: Mapper<AttendanceRecord, UpsertAttendanceDTO>;
